### ISSUE TITLE
About Sharkle

### ISSUE THREAD

**Issue by SticksAndFirecrackers** [SamusAranX/Sharkle#2]
The problem i have with him is that he doesn't stay on the desktop and follows me when i open other programs such as Chrome also is there any way i can customize his size since he is far too big. 

Thanks in advance.

**Comment by SamusAranX** [comment]
What do you mean by "follow"? Sharkle should behave like any other window and move to the background once another app is focused or opened.

Also, what's your desktop resolution? I modeled Sharkle's size off of screenshots of NITW, so he should be just as big on your desktop as he is in the game. If that's still too large, your resolution is probably too small, sorry. :/
